#!/usr/bin/env python

# Import pycurve libs
import pycurve.client
import pycurve.parser

def main():
    '''
    The main function
    '''
    opts = pycurve.parser.parse()
    client = pycurve.client.Client(opts)
    client.send('foobar')
